{
 "title": "GCloud CMCD v2",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cmcd_key_cid",
    "label": "Content ID",
    "query": {}
   },
   {
    "name": "cmcd_key_sid",
    "label": "Session ID",
    "query": {}
   },
   {
    "name": "request_country_code",
    "label": "Country Code",
    "query": {}
   },
   {
    "name": "request_browser_name",
    "label": "Browser Name",
    "query": {}
   },
   { "name": "table_name", "label": "Table Name", "query": "cmcdv2-bigquery.cmcd.cmcd" }
  ]
 },
 "panels": [
  {
   "title": "CMCD Messages over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "project": "gloud-cmcd-v2",
     "rawSql": "-- Returns the count of requests over time.\n-- Use this for a \"Requests per minute/hour\" graph.\nSELECT\n  $__timeGroup(request_datetime, '1m') AS time, -- Groups data into time buckets (e.g., 5 minutes)\n  COUNT(*) AS requests_over_time\nFROM\n  `${table_name}`\nWHERE\n  $__timeFilter(request_datetime) -- Filters data based on the Grafana dashboard's time range\n  AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n  AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n  AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n  AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')\nGROUP BY\n  time\nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "Buffer starvation distribution by Country",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "project": "gloud-cmcd-v2",
     "rawSql": "WITH StarvationEvents AS (\n  SELECT\n    request_country_name\n  FROM\n    `${table_name}`\n  WHERE\n    $__timeFilter(request_datetime)\n    AND cmcd_key_bs IS TRUE\n    AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n    AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n    AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n    AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')\n)\nSELECT\n  request_country_name AS country,\n  (COUNT(*) * 100.0 / (SELECT COUNT(*) FROM StarvationEvents)) AS percentage\nFROM\n  StarvationEvents\nWHERE\n  request_country_name IS NOT NULL\nGROUP BY\n  country\nORDER BY\n  percentage DESC\nLIMIT 20"
    }
   ]
  },
  {
   "title": "Buffer starvation distribution by Content ID",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "project": "gloud-cmcd-v2",
     "rawSql": "WITH StarvationEvents AS (\n  SELECT\n    cmcd_key_cid\n  FROM\n    `${table_name}`\n  WHERE\n    $__timeFilter(request_datetime)\n    AND cmcd_key_bs IS TRUE\n    AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n    AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n    AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n    AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')\n)\nSELECT\n  cmcd_key_cid AS metric,\n  (COUNT(*) * 100.0 / (SELECT COUNT(*) FROM StarvationEvents)) AS percentage\nFROM\n  StarvationEvents\nWHERE\n  cmcd_key_cid IS NOT NULL\nGROUP BY\n  metric\nORDER BY\n  percentage DESC\nLIMIT 20"
    }
   ]
  },
  {
   "title": "Buffer starvation distribution by ASN",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "project": "gloud-cmcd-v2",
     "rawSql": "WITH StarvationEvents AS (\n  SELECT\n    request_asn_organization\n  FROM\n    `${table_name}`\n  WHERE\n    $__timeFilter(request_datetime)\n    AND cmcd_key_bs IS TRUE\n    AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n    AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n    AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n    AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')\n)\nSELECT\n  request_asn_organization AS metric,\n  (COUNT(*) * 100.0 / (SELECT COUNT(*) FROM StarvationEvents)) AS percentage\nFROM\n  StarvationEvents\nWHERE\n  request_asn_organization IS NOT NULL\nGROUP BY\n  metric\nORDER BY\n  percentage DESC\nLIMIT 20"
    }
   ]
  },
  {
   "title": "Buffer starvation distribution by CDN",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "project": "gloud-cmcd-v2",
     "rawSql": "WITH StarvationEvents AS (\n  SELECT\n    cmcd_key_url_domain\n  FROM\n    `${table_name}`\n  WHERE\n    $__timeFilter(request_datetime)\n    AND cmcd_key_bs IS TRUE\n    AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n    AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n    AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n    AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')  \n  )\nSELECT\n  cmcd_key_url_domain AS cdn,\n  (COUNT(*) * 100.0 / (SELECT COUNT(*) FROM StarvationEvents)) AS percentage\nFROM\n  StarvationEvents\nWHERE\n  cmcd_key_url_domain IS NOT NULL\nGROUP BY\n  cdn\nORDER BY\n  percentage DESC\nLIMIT 20"
    }
   ]
  },
  {
   "title": "Rebufering Ratio",
   "type": "gauge",
   "description": "Measures what percentage of total viewing time a user spent waiting for the video to load (rebuffering). A low value is ideal.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "gloud-cmcd-v2",
     "rawSql": "WITH Durations AS (\n  SELECT\n    cmcd_key_sta,\n    -- Calculate duration of each state\n    TIMESTAMP_DIFF(\n      LEAD(request_datetime, 1) OVER (PARTITION BY cmcd_key_sid ORDER BY request_datetime),\n      request_datetime,\n      MILLISECOND\n    ) AS duration_ms\n  FROM\n    `${table_name}`\n  WHERE\n    $__timeFilter(request_datetime)\n    AND cmcd_key_sta IS NOT NULL\n    AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n    AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n    AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n    AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')\n),\nAggregatedTime AS (\n  SELECT\n    -- Sum duration for 'buffering' state\n    SUM(IF(cmcd_key_sta = 'r', duration_ms, 0)) AS buffering_time_ms,\n    -- Sum duration for 'playing' state\n    SUM(IF(cmcd_key_sta = 'p' OR cmcd_key_sta = 'k' OR cmcd_key_sta = 's' OR cmcd_key_sta='a', duration_ms, 0)) AS playing_time_ms\n  FROM Durations\n)\nSELECT\n  -- Calculate ratio: (buffering_time / (playing_time + buffering_time)) * 100\n  SAFE_DIVIDE(buffering_time_ms * 100, playing_time_ms + buffering_time_ms) AS rebuffering_ratio_percentage\nFROM\n  AggregatedTime\n"
    }
   ]
  },
  {
   "title": "Buffer starvation distribution by Session ID",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "project": "gloud-cmcd-v2",
     "rawSql": "WITH StarvationEvents AS (\n  SELECT\n    cmcd_key_sid\n  FROM\n    `${table_name}`\n  WHERE\n    $__timeFilter(request_datetime)\n    AND cmcd_key_bs IS TRUE\n    AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n    AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n    AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n    AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')\n)\nSELECT\n  cmcd_key_sid AS metric,\n  (COUNT(*) * 100.0 / (SELECT COUNT(*) FROM StarvationEvents)) AS percentage\nFROM\n  StarvationEvents\nWHERE\n  cmcd_key_sid IS NOT NULL\nGROUP BY\n  metric\nORDER BY\n  percentage DESC\nLIMIT 20"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "cmcd",
     "project": "gloud-cmcd-v2",
     "rawSql": "SELECT\n  request_country_code AS metric, -- Uses 2-letter country code\n  COUNT(DISTINCT cmcd_key_sid) AS value\nFROM\n  `${table_name}`\nWHERE\n  $__timeFilter(request_datetime)\n  AND request_country_code IS NOT NULL\n  AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n  AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n  AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n  AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')  \nGROUP BY\n  metric"
    }
   ]
  },
  {
   "title": "Browsers",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cmcd",
     "project": "gloud-cmcd-v2",
     "rawSql": "SELECT\n  request_browser_name,\n  COUNT(distinct cmcd_key_sid),\nFROM\n  `${table_name}`\nWHERE\n  $__timeFilter(request_datetime)\n  AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n  AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n  AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n  AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')\nGROUP BY\n  request_browser_name\nLIMIT\n  50"
    }
   ]
  },
  {
   "title": "Sessions per country",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cmcd",
     "project": "gloud-cmcd-v2",
     "rawSql": "SELECT\n  request_country_name,\n  COUNT(distinct cmcd_key_sid),\nFROM\n  `${table_name}`\nWHERE\n  $__timeFilter(request_datetime)\n  AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n  AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n  AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n  AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')  \nGROUP BY\n  request_country_name\nLIMIT\n  50"
    }
   ]
  },
  {
   "title": "Top 10 ASNs by Sessions",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 34 },
   "targets": [
    {
     "dataset": "cmcd",
     "project": "gloud-cmcd-v2",
     "rawSql": "SELECT\n  request_asn_organization AS ASN,\n  COUNT(DISTINCT cmcd_key_sid) AS sessions,\n  AVG(cmcd_key_mtp) AS mean_throughput\nFROM\n  `${table_name}`\nWHERE\n  $__timeFilter(request_datetime)\n  AND request_asn_organization IS NOT NULL\n  AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n  AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n  AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n  AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')  \nGROUP BY\n  ASN\nORDER BY\n  sessions DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "# Sessions over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "cmcd",
     "project": "gloud-cmcd-v2",
     "rawSql": "SELECT\n  $__timeGroup(request_datetime, '1m') AS time,\n  COUNT(DISTINCT cmcd_key_sid) AS unique_sessions\nFROM\n  `${table_name}`\nWHERE\n  $__timeFilter(request_datetime)\n  AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n  AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n  AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n  AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')  \nGROUP BY\n  time\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "Video Throughput Histogram",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "dataset": "cmcd",
     "project": "gloud-cmcd-v2",
     "rawSql": "SELECT\n  ANY_VALUE(cmcd_key_mtp)\nFROM\n  `${table_name}`\nWHERE\n  $__timeFilter(request_datetime)\n  AND cmcd_key_ot = 'v'\n  AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n  AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n  AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n  AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')  \nGROUP BY\n  request_datetime\nLIMIT\n  50"
    }
   ]
  },
  {
   "title": "Video Bitrate vs. Throughput (MIN, AVG, MAX)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "project": "gloud-cmcd-v2",
     "rawSql": "SELECT\n  $__timeGroup(request_datetime, '1m') AS time,\n  AVG(cmcd_key_br) AS selected_bitrate_kbps,\n  AVG(cmcd_key_mtp) AS avg_measured_throughput_kbps,\n  MIN(cmcd_key_mtp) AS min_measured_throughput_kbps,\n  MAX(cmcd_key_mtp) AS max_measured_throughput_kbps\nFROM\n  `${table_name}`\nWHERE\n  $__timeFilter(request_datetime)\n  AND cmcd_key_br IS NOT NULL\n  AND cmcd_key_mtp IS NOT NULL\n  AND cmcd_key_ot = 'v'\n  AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n  AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n  AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n  AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')\nGROUP BY\n  time\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "Video Throughput (MIN, AVG, MAX)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "dataset": "cmcd",
     "project": "gloud-cmcd-v2",
     "rawSql": "SELECT\n  $__timeGroup(request_datetime, '1m') AS time,\n  AVG(cmcd_key_mtp) AS average_throughput_kbps,\n  MAX(cmcd_key_mtp) AS max_throughput_kbps,\n  MIN(cmcd_key_mtp) AS miN_throughput_kbps\nFROM\n  `${table_name}`\nWHERE\n  $__timeFilter(request_datetime)\n  AND cmcd_key_mtp IS NOT NULL\n  AND cmcd_key_ot = 'v'\n  AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n  AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n  AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n  AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')\nGROUP BY\n  time\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "Video Buffer (MIN, AVG, MAX)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "project": "gloud-cmcd-v2",
     "rawSql": "SELECT\n  $__timeGroup(request_datetime, '10s') AS time,\n  AVG(cmcd_key_bl) AS Average_Buffer_ms,\n  MAX(cmcd_key_bl) AS max_Buffer_ms,\n  MIN(cmcd_key_bl) AS min_Buffer_ms\nFROM\n  `${table_name}`\nWHERE\n  $__timeFilter(request_datetime)\n  AND cmcd_key_bl IS NOT NULL\n  AND cmcd_key_ot = 'v'\n  AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n  AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n  AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n  AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')\nGROUP BY\n  time\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "# Buffer Starved",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "cmcd",
     "project": "gloud-cmcd-v2",
     "rawSql": "SELECT\n  $__timeGroup(request_datetime, '1m') AS time,\n  COUNTIF(cmcd_key_bs IS TRUE) AS Buffer_Starvations\nFROM\n  `${table_name}`\nWHERE\n  $__timeFilter(request_datetime)\n  AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n  AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n  AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n  AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')  \nGROUP BY\n  time\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "Video Bitrate Changes Timeline per Session (select a session)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "kbps" } },
   "targets": [
    {
     "project": "gloud-cmcd-v2",
     "rawSql": "SELECT\n  $__timeGroup(request_datetime, '10s') AS time,\n  cmcd_key_br AS br,\n  cmcd_key_mtp as mtp\nFROM\n  `${table_name}`\nWHERE\n  $__timeFilter(request_datetime)\n  AND cmcd_key_sid = '${cmcd_key_sid:raw}' -- Filter by the session ID selected in the dashboard\n  AND cmcd_key_br IS NOT NULL\n  AND cmcd_key_ot = 'v'\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "Playback status visualizer (select a session id)",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "project": "gloud-cmcd-v2",
     "rawSql": "SELECT\n  request_datetime AS time,\n  cmcd_key_sta AS state -- The state name (e.g., 'playing', 'paused')\nFROM\n  `${table_name}`\nWHERE\n  $__timeFilter(request_datetime)\n  AND cmcd_key_sid = '${cmcd_key_sid:raw}' -- Filter by the session ID selected in the dashboard\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "Latency (MIN, AVG, MAX)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "cmcd",
     "project": "gloud-cmcd-v2",
     "rawSql": "SELECT\n  $__timeGroup(request_datetime, '10s') AS time,\n  AVG(cmcd_key_ltc) AS avg_latency,\nFROM\n  `${table_name}`\nWHERE\n  $__timeFilter(request_datetime)\n  AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n  AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n  AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n  AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')  \nGROUP BY\n  time\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "Latency Distribution by Content ID",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {
     "project": "gloud-cmcd-v2",
     "rawSql": "WITH LatencyData AS (\n  SELECT\n    cmcd_key_cid,\n    cmcd_key_ltc\n  FROM\n    `${table_name}`\n  WHERE\n    $__timeFilter(request_datetime)\n    AND cmcd_key_cid IS NOT NULL\n    AND cmcd_key_ltc IS NOT NULL\n    AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n    AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n    AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n    AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')\n),\nPercentiles AS (\n  SELECT\n    cmcd_key_cid,\n    -- Calculate approximate percentiles for latency\n    APPROX_QUANTILES(cmcd_key_ltc, 100) AS quantiles\n  FROM\n    LatencyData\n  GROUP BY\n    cmcd_key_cid\n)\nSELECT\n  p.cmcd_key_cid AS content_id,\n  -- Extract specific percentiles from the array\n  p.quantiles[OFFSET(50)] AS p50_latency,\n  p.quantiles[OFFSET(75)] AS p75_latency,\n  p.quantiles[OFFSET(95)] AS p95_latency,\n  p.quantiles[OFFSET(99)] AS p99_latency,\n  -- Calculate other stats\n  AVG(ld.cmcd_key_ltc) AS avg_latency,\n  MIN(ld.cmcd_key_ltc) AS min_latency,\n  MAX(ld.cmcd_key_ltc) AS max_latency\nFROM\n  Percentiles p\nJOIN\n  LatencyData ld ON p.cmcd_key_cid = ld.cmcd_key_cid\nGROUP BY\n  p.cmcd_key_cid,\n  p50_latency,\n  p75_latency,\n  p95_latency,\n  p99_latency\nORDER BY\n  p95_latency DESC"
    }
   ]
  },
  {
   "title": "Meida Start Delay Histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "cmcd",
     "project": "gloud-cmcd-v2",
     "rawSql": "SELECT\n  ANY_VALUE(cmcd_key_msd)\nFROM\n  `${table_name}`\nWHERE\n  $__timeFilter(request_datetime)\n  AND cmcd_key_sid IS NOT NULL\n  AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n  AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n  AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n  AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')\nGROUP BY\n  cmcd_key_sid\nLIMIT\n  200"
    }
   ]
  },
  {
   "title": "Media Start Delay (MIN, AVG, MAX)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "cmcd",
     "project": "gloud-cmcd-v2",
     "rawSql": "SELECT\n  $__timeGroup(request_datetime, '10s') AS time,\n  MIN(cmcd_key_msd) AS min_media_start_delay,\n  AVG(cmcd_key_msd) AS avg_media_start_delay,\n  MAX(cmcd_key_msd) AS max_media_start_delay \nFROM\n  `${table_name}`\nWHERE\n  $__timeFilter(request_datetime)\n  AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n  AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n  AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n  AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')  \nGROUP BY\n  time\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "Content",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 100 },
   "targets": [
    {
     "dataset": "cmcd",
     "project": "gloud-cmcd-v2",
     "rawSql": "SELECT\n  ANY_VALUE(cmcd_key_cid),\n  COUNT(DISTINCT cmcd_key_sid),\n  AVG(cmcd_key_msd),\n  COUNT(cmcd_key_bs),\n  AVG(cmcd_key_ltc),\n  AVG(cmcd_key_mtp),\n  AVG(cmcd_key_ttfb),\n  AVG(cmcd_key_ttlb)\nFROM\n  `${table_name}`\nWHERE\n  $__timeFilter(request_datetime)\n  AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n  AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n  AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n  AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')  \nGROUP BY\n  cmcd_key_cid\nLIMIT\n  50"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 108 },
   "targets": [
    {
     "dataset": "cmcd",
     "project": "gloud-cmcd-v2",
     "rawSql": "SELECT\n  ANY_VALUE(cmcd_key_sid),\n  ANY_VALUE(cmcd_key_cid),\n  ANY_VALUE(cmcd_key_msd),\n  COUNT(cmcd_key_bs),\n  AVG(cmcd_key_ltc),\n  AVG(cmcd_key_mtp),\n  AVG(cmcd_key_ttfb),\n  AVG(cmcd_key_ttlb)\nFROM\n  `${table_name}`\nWHERE\n  $__timeFilter(request_datetime)\n  AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n  AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n  AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n  AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')  \nGROUP BY\n  cmcd_key_sid\nLIMIT\n  50"
    }
   ]
  },
  {
   "title": "User Agent Performance",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 115 },
   "targets": [
    {
     "dataset": "cmcd",
     "project": "gloud-cmcd-v2",
     "rawSql": "SELECT\n  ANY_VALUE(request_user_agent),\n  COUNT(DISTINCT cmcd_key_sid),\n  AVG(cmcd_key_msd),\n  COUNT(cmcd_key_bs),\n  AVG(cmcd_key_ltc),\n  AVG(cmcd_key_mtp),\n  AVG(cmcd_key_ttfb),\n  AVG(cmcd_key_ttlb)\nFROM\n  `${table_name}`\nWHERE\n  $__timeFilter(request_datetime)\n  AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n  AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n  AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n  AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')  \nGROUP BY\n  request_user_agent\nLIMIT\n  50"
    }
   ]
  },
  {
   "title": "CDN Performance",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 122 },
   "targets": [
    {
     "dataset": "cmcd",
     "project": "gloud-cmcd-v2",
     "rawSql": "SELECT\n  ANY_VALUE(cmcd_key_url_domain),\n  AVG(cmcd_key_ttfb),\n  AVG(cmcd_key_ttlb),\n  AVG(cmcd_key_mtp),\n  COUNT(cmcd_key_bs),\n  COUNT(DISTINCT cmcd_key_sid)\nFROM\n  `${table_name}`\nWHERE\n  $__timeFilter(request_datetime)\n  AND cmcd_key_url_domain IS NOT NULL\n  AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n  AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n  AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n  AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')  \nGROUP BY\n  cmcd_key_url_domain"
    }
   ]
  },
  {
   "title": "CDN HTTP Response Codes (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "project": "gloud-cmcd-v2",
     "rawSql": "SELECT\n  $__timeGroup(request_datetime, '1m') AS time,\n  SAFE_DIVIDE(COUNTIF(cmcd_key_rc >= 200 AND cmcd_key_rc < 300) * 100.0, COUNT(*)) AS HTTP_Success,\n  SAFE_DIVIDE(COUNTIF(cmcd_key_rc >= 400 AND cmcd_key_rc < 500) * 100.0, COUNT(*)) AS HTTP_Client_Error,\n  SAFE_DIVIDE(COUNTIF(cmcd_key_rc >= 500 AND cmcd_key_rc < 600) * 100.0, COUNT(*)) AS HTTP_Server_Error\nFROM\n  `${table_name}`\nWHERE\n  $__timeFilter(request_datetime)\n  AND cmcd_key_rc IS NOT NULL\n  AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n  AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n  AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n  AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')  \nGROUP BY\n  time\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "CDN Time to First Byte",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "project": "gloud-cmcd-v2",
     "rawSql": "SELECT\n  $__timeGroup(request_datetime, '1m') AS time,\n  AVG(cmcd_key_ttfb) AS avg_ttfb,\n  MIN(cmcd_key_ttfb) AS min_ttfb,\n  MAX(cmcd_key_ttfb) AS max_ttfb\nFROM\n  `${table_name}`\nWHERE\n  $__timeFilter(request_datetime)\n  AND cmcd_key_ttfb IS NOT NULL\n  AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n  AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n  AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n  AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')  \nGROUP BY\n  time\nORDER BY\n  time"
    }
   ]
  }
 ]
}