{
 "title": "CMCD for Research",
 "time": { "from": "2025-10-10T03:00:00.000Z", "to": "2025-10-12T02:59:59.000Z" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cmcd_key_cid",
    "label": "Content ID",
    "query": {}
   },
   {
    "name": "cmcd_key_sid",
    "label": "Session ID",
    "query": {}
   },
   {
    "name": "request_country_code",
    "label": "Country Code",
    "query": {}
   },
   {
    "name": "request_browser_name",
    "label": "Browser Name",
    "query": {}
   },
   { "name": "table_name", "label": "Table Name", "query": "ibc-2025-low-latency.cmcd.cmcd" },
   { "name": "time_aggregate", "label": "Time aggregate", "query": "1s,5s,10s,30s,1m,10m" }
  ]
 },
 "panels": [
  {
   "title": "Total sessions registered",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cmcd",
     "project": "ibc-2025-low-latency",
     "rawSql": "SELECT\n  COUNT(distinct cmcd_key_sid)\nFROM\n  ${table_name}\nWHERE\n  $__timeFilter(request_datetime)   \n  AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n  AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n  AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n  AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')  \nLIMIT\n  50"
    }
   ]
  },
  {
   "title": "Total sessions filtered",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cmcd",
     "project": "ibc-2025-low-latency",
     "rawSql": "SELECT\n  COUNT(distinct cmcd_key_sid)\nFROM\n  ${table_name}\nWHERE\n  $__timeFilter(request_datetime)   \n  AND cmcd_key_ltc < 15000\n  AND cmcd_key_ltc > 0\n  AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n  AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n  AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n  AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')  \nLIMIT\n  50"
    }
   ]
  },
  {
   "title": "Browsers",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cmcd",
     "project": "ibc-2025-low-latency",
     "rawSql": "SELECT\n  request_browser_name,\n  COUNT(distinct cmcd_key_sid),\nFROM\n  ${table_name}\nWHERE\n  $__timeFilter(request_datetime)\n  \n  AND cmcd_key_ltc > 0\n  AND cmcd_key_ltc < 15000    \n  AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n  AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n  AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n  AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')\nGROUP BY\n  request_browser_name\nLIMIT\n  50"
    }
   ]
  },
  {
   "title": "Sessions per country",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cmcd",
     "project": "ibc-2025-low-latency",
     "rawSql": "SELECT\n  request_country_name,\n  COUNT(distinct cmcd_key_sid),\nFROM\n  ${table_name}\nWHERE\n  $__timeFilter(request_datetime)\n  AND cmcd_key_ltc > 0\n  AND cmcd_key_ltc < 15000      \n  AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n  AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n  AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n  AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')  \nGROUP BY\n  request_country_name\nLIMIT\n  50"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "cmcd",
     "project": "ibc-2025-low-latency",
     "rawSql": "SELECT\n  request_country_code AS metric, -- Uses 2-letter country code\n  COUNT(DISTINCT cmcd_key_sid) AS value\nFROM\n  ${table_name}\nWHERE\n  $__timeFilter(request_datetime)\n  AND request_country_code IS NOT NULL\n  AND cmcd_key_ltc > 0\n  AND cmcd_key_ltc < 15000  \n  AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n  AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n  AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n  AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')  \nGROUP BY\n  metric"
    }
   ]
  },
  {
   "title": "# Sessions over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "cmcd",
     "project": "ibc-2025-low-latency",
     "rawSql": "SELECT\n  $__timeGroup(request_datetime, '$time_aggregate') AS time,\n  COUNT(DISTINCT cmcd_key_sid) AS unique_sessions\nFROM\n  ${table_name}\nWHERE\n  $__timeFilter(request_datetime)\n  AND cmcd_key_ltc > 0\n  AND cmcd_key_ltc < 15000  \n  AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n  AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n  AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n  AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')  \nGROUP BY\n  time\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "Top 10 ASNs by Sessions",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "dataset": "cmcd",
     "project": "ibc-2025-low-latency",
     "rawSql": "SELECT\n  request_asn_organization AS ASN,\n  COUNT(DISTINCT cmcd_key_sid) AS sessions,\n  AVG(cmcd_key_mtp) AS mean_throughput,\n  COUNTIF( (cmcd_key_bs IS TRUE OR cmcd_key_sta = \"r\" ) AND cmcd_key_su IS NOT TRUE and cmcd_key_ot = \"v\") AS non_startup_buffer_starvations\nFROM\n  ${table_name}\nWHERE\n  $__timeFilter(request_datetime)\n  AND request_asn_organization IS NOT NULL\n  AND cmcd_key_ltc > 0\n  AND cmcd_key_ltc < 15000      \n  AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n  AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n  AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n  AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')  \nGROUP BY\n  ASN\nORDER BY\n  sessions DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Content",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "dataset": "cmcd",
     "project": "ibc-2025-low-latency",
     "rawSql": "SELECT\n  ANY_VALUE(cmcd_key_cid),\n  COUNT(DISTINCT cmcd_key_sid),\n  COUNT(cmcd_key_cid),\n  AVG(cmcd_key_msd),\n  COUNTIF( (cmcd_key_bs IS TRUE OR cmcd_key_sta = \"r\") AND cmcd_key_su IS NOT TRUE AND cmcd_key_ot= \"v\"),\n  COUNTIF( (cmcd_key_bs IS TRUE OR cmcd_key_sta = \"r\") AND cmcd_key_su IS NOT TRUE AND cmcd_key_ot= \"v\") / COUNT(DISTINCT cmcd_key_sid),\n  AVG(CASE WHEN cmcd_key_sta = \"p\" THEN cmcd_key_ltc ELSE NULL END),\n  AVG(cmcd_key_mtp),\n  AVG(cmcd_key_ttfb),\n  AVG(cmcd_key_ttlb)\nFROM\n  ${table_name}\nWHERE\n  $__timeFilter(request_datetime)\n  AND cmcd_key_cid IS NOT NULL\n  AND cmcd_key_ltc > 0\n  AND cmcd_key_ltc < 15000\n  AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n  AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n  AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n  AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')  \nGROUP BY\n  cmcd_key_cid\nLIMIT\n  50"
    }
   ]
  },
  {
   "title": "Latency Distribution by Content ID",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "project": "ibc-2025-low-latency",
     "rawSql": "WITH LatencyData AS (\n  SELECT\n    cmcd_key_sid,\n    cmcd_key_cid,\n    cmcd_key_ltc\n  FROM\n    ${table_name}\n  WHERE\n    $__timeFilter(request_datetime)\n    AND cmcd_key_sid IS NOT NULL\n    AND cmcd_key_cid IS NOT NULL\n    AND cmcd_key_ltc IS NOT NULL\n    AND cmcd_key_ltc > 0\n    AND cmcd_key_ltc < 15000\n    AND (cmcd_key_sta = \"p\" OR cmcd_key_sta = \"s\")    \n    AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n    AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n    AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n    AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')\n),\nPercentiles AS (\n  SELECT\n    cmcd_key_cid,\n    -- Calculate approximate percentiles for latency\n    APPROX_QUANTILES(cmcd_key_ltc, 100) AS quantiles\n  FROM\n    LatencyData\n  GROUP BY\n    cmcd_key_cid\n)\nSELECT\n  p.cmcd_key_cid AS content_id,\n  -- Extract specific percentiles from the array\n  p.quantiles[OFFSET(25)] AS p25_latency,\n  p.quantiles[OFFSET(35)] AS p35_latency,\n  p.quantiles[OFFSET(50)] AS p50_latency,\n  p.quantiles[OFFSET(75)] AS p75_latency,\n  p.quantiles[OFFSET(95)] AS p95_latency,\n  p.quantiles[OFFSET(99)] AS p99_latency,\n  -- Calculate other stats\n  AVG(ld.cmcd_key_ltc) AS avg_latency,\n  STDDEV(ld.cmcd_key_ltc) AS stddev_latency,\n  MIN(ld.cmcd_key_ltc) AS min_latency,\n  MAX(ld.cmcd_key_ltc) AS max_latency\nFROM\n  Percentiles p\nJOIN\n  LatencyData ld ON p.cmcd_key_cid = ld.cmcd_key_cid\nGROUP BY\n  p.cmcd_key_cid,\n  p25_latency,\n  p35_latency,\n  p50_latency,\n  p75_latency,\n  p95_latency,\n  p99_latency\nORDER BY\n  p95_latency DESC"
    }
   ]
  },
  {
   "title": "Startup Time distribution by Content ID",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {
     "project": "ibc-2025-low-latency",
     "rawSql": "WITH Data AS (\n  SELECT\n    cmcd_key_cid,\n    cmcd_key_msd\n  FROM\n    ${table_name}\n  WHERE\n    $__timeFilter(request_datetime)\n    AND cmcd_key_cid IS NOT NULL\n    AND cmcd_key_msd IS NOT NULL\n    AND cmcd_key_msd < 6000\n    AND cmcd_key_ltc > 0\n    AND cmcd_key_ltc < 15000    \n    AND (cmcd_key_sta = \"p\" OR cmcd_key_sta = \"s\")    \n    AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n    AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n    AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n    AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')\n),\nPercentiles AS (\n  SELECT\n    cmcd_key_cid,\n    -- Calculate approximate percentiles for Media start Delay\n    APPROX_QUANTILES(cmcd_key_msd, 100) AS quantiles\n  FROM\n    Data\n  GROUP BY\n    cmcd_key_cid\n)\nSELECT\n  p.cmcd_key_cid AS content_id,\n  -- Extract specific percentiles from the array\n  p.quantiles[OFFSET(25)] AS p25_msd,\n  p.quantiles[OFFSET(35)] AS p35_msd,\n  p.quantiles[OFFSET(50)] AS p50_msd,\n  p.quantiles[OFFSET(75)] AS p75_msd,\n  p.quantiles[OFFSET(95)] AS p95_msd,\n  p.quantiles[OFFSET(99)] AS p99_msd,\n  -- Calculate other stats\n  AVG(ld.cmcd_key_msd) AS avg_msd,\n  STDDEV(ld.cmcd_key_msd) AS stddev_msd,\n  MIN(ld.cmcd_key_msd) AS min_msd,\n  MAX(ld.cmcd_key_msd) AS max_msd\nFROM\n  Percentiles p\nJOIN\n  Data ld ON p.cmcd_key_cid = ld.cmcd_key_cid\nGROUP BY\n  p.cmcd_key_cid,\n  p25_msd,\n  p35_msd,\n  p50_msd,\n  p75_msd,\n  p95_msd,\n  p99_msd\nORDER BY\n  p95_msd DESC"
    }
   ]
  },
  {
   "title": "TTFB distribution by Content ID",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {
     "project": "ibc-2025-low-latency",
     "rawSql": "WITH Data AS (\n  SELECT\n    cmcd_key_cid,\n    cmcd_key_ttfb as key_value\n  FROM\n    ${table_name}\n  WHERE\n    $__timeFilter(request_datetime)\n    AND cmcd_key_cid IS NOT NULL\n    AND cmcd_key_ttfb IS NOT NULL\n    AND cmcd_key_ttfb > 0\n    AND cmcd_key_ltc > 0\n    AND cmcd_key_ltc < 15000    \n    AND (cmcd_key_sta = \"p\" OR cmcd_key_sta = \"s\")    \n    AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n    AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n    AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n    AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')\n),\nPercentiles AS (\n  SELECT\n    d.cmcd_key_cid,\n    -- Calculate approximate percentiles for Media start Delay\n    APPROX_QUANTILES(d.key_value, 100) AS quantiles\n  FROM\n    Data d\n  GROUP BY\n    cmcd_key_cid\n)\nSELECT\n  p.cmcd_key_cid AS content_id,\n  -- Extract specific percentiles from the array\n  p.quantiles[OFFSET(25)] AS p25,\n  p.quantiles[OFFSET(35)] AS p35,\n  p.quantiles[OFFSET(50)] AS p50,\n  p.quantiles[OFFSET(75)] AS p75,\n  p.quantiles[OFFSET(95)] AS p95,\n  p.quantiles[OFFSET(99)] AS p99,\n  -- Calculate other stats\n  AVG(ld.key_value) AS key_avg,\n  STDDEV(ld.key_value) AS key_stddev,\n  MIN(ld.key_value) AS key_min,\n  MAX(ld.key_value) AS key_max\nFROM\n  Percentiles p\nJOIN\n  Data ld ON p.cmcd_key_cid = ld.cmcd_key_cid\nGROUP BY\n  p.cmcd_key_cid,\n  p25,\n  p35,\n  p50,\n  p75,\n  p95,\n  p99\nORDER BY\n  p95 DESC"
    }
   ]
  },
  {
   "title": "TTLB distribution by Content ID",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 105 },
   "targets": [
    {
     "project": "ibc-2025-low-latency",
     "rawSql": "WITH Data AS (\n  SELECT\n    cmcd_key_cid,\n    cmcd_key_ttlb as key_value\n  FROM\n    ${table_name}\n  WHERE\n    $__timeFilter(request_datetime)\n    AND cmcd_key_cid IS NOT NULL\n    AND cmcd_key_ttlb IS NOT NULL\n    AND cmcd_key_ttlb > 0\n    AND cmcd_key_ltc > 0\n    AND cmcd_key_ltc < 15000\n    AND (cmcd_key_sta = \"p\" OR cmcd_key_sta = \"s\")    \n    AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n    AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n    AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n    AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')\n),\nPercentiles AS (\n  SELECT\n    d.cmcd_key_cid,\n    -- Calculate approximate percentiles for Media start Delay\n    APPROX_QUANTILES(d.key_value, 100) AS quantiles\n  FROM\n    Data d\n  GROUP BY\n    cmcd_key_cid\n)\nSELECT\n  p.cmcd_key_cid AS content_id,\n  -- Extract specific percentiles from the array\n  p.quantiles[OFFSET(25)] AS p25,\n  p.quantiles[OFFSET(35)] AS p35,\n  p.quantiles[OFFSET(50)] AS p50,\n  p.quantiles[OFFSET(75)] AS p75,\n  p.quantiles[OFFSET(95)] AS p95,\n  p.quantiles[OFFSET(99)] AS p99,\n  -- Calculate other stats\n  AVG(ld.key_value) AS key_avg,\n  STDDEV(ld.key_value) AS key_stddev,\n  MIN(ld.key_value) AS key_min,\n  MAX(ld.key_value) AS key_max\nFROM\n  Percentiles p\nJOIN\n  Data ld ON p.cmcd_key_cid = ld.cmcd_key_cid\nGROUP BY\n  p.cmcd_key_cid,\n  p25,\n  p35,\n  p50,\n  p75,\n  p95,\n  p99\nORDER BY\n  p95 DESC"
    }
   ]
  },
  {
   "title": "Video Bitrate distribution by Content ID",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 124 },
   "targets": [
    {
     "project": "ibc-2025-low-latency",
     "rawSql": "WITH Data AS (\n  SELECT\n    cmcd_key_cid,\n    cmcd_key_br as key_value\n  FROM\n    ${table_name}\n  WHERE\n    $__timeFilter(request_datetime)\n    AND cmcd_key_cid IS NOT NULL\n    AND cmcd_key_ttlb IS NOT NULL\n    AND cmcd_key_ttlb > 0\n    AND cmcd_key_ltc > 0\n    AND cmcd_key_ltc < 15000\n    AND cmcd_key_ot = \"v\"\n    AND (cmcd_key_sta = \"p\" OR cmcd_key_sta = \"s\")    \n    AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n    AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n    AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n    AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')\n),\nPercentiles AS (\n  SELECT\n    d.cmcd_key_cid,\n    -- Calculate approximate percentiles for Media start Delay\n    APPROX_QUANTILES(d.key_value, 100) AS quantiles\n  FROM\n    Data d\n  GROUP BY\n    cmcd_key_cid\n)\nSELECT\n  p.cmcd_key_cid AS content_id,\n  -- Extract specific percentiles from the array\n  p.quantiles[OFFSET(25)] AS p25,\n  p.quantiles[OFFSET(35)] AS p35,\n  p.quantiles[OFFSET(50)] AS p50,\n  p.quantiles[OFFSET(75)] AS p75,\n  p.quantiles[OFFSET(95)] AS p95,\n  p.quantiles[OFFSET(99)] AS p99,\n  -- Calculate other stats\n  AVG(ld.key_value) AS key_avg,\n  STDDEV(ld.key_value) AS key_stddev,\n  MIN(ld.key_value) AS key_min,\n  MAX(ld.key_value) AS key_max\nFROM\n  Percentiles p\nJOIN\n  Data ld ON p.cmcd_key_cid = ld.cmcd_key_cid\nGROUP BY\n  p.cmcd_key_cid,\n  p25,\n  p35,\n  p50,\n  p75,\n  p95,\n  p99\nORDER BY\n  p95 DESC"
    }
   ]
  },
  {
   "title": "Startup Time Histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "cmcd",
     "project": "ibc-2025-low-latency",
     "rawSql": "SELECT\n  ANY_VALUE(cmcd_key_msd)\nFROM\n  ${table_name}\nWHERE\n  $__timeFilter(request_datetime)\n  AND cmcd_key_sid IS NOT NULL\n  AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n  AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n  AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n  AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')\nGROUP BY\n  cmcd_key_sid\n"
    }
   ]
  },
  {
   "title": "Startup Time (MIN, AVG, MAX)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "cmcd",
     "project": "ibc-2025-low-latency",
     "rawSql": "SELECT\n  $__timeGroup(request_datetime, '$time_aggregate') AS time,\n  MIN(cmcd_key_msd) AS min_media_start_delay,\n  AVG(cmcd_key_msd) AS avg_media_start_delay,\n  MAX(cmcd_key_msd) AS max_media_start_delay \nFROM\n  ${table_name}\nWHERE\n  $__timeFilter(request_datetime)\n  AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n  AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n  AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n  AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')  \nGROUP BY\n  time\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "CDN Performance",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 150 },
   "targets": [
    {
     "dataset": "cmcd",
     "project": "ibc-2025-low-latency",
     "rawSql": "SELECT\n  ANY_VALUE(cmcd_key_url_domain),\n  AVG(cmcd_key_ttfb),\n  AVG(cmcd_key_ttlb),\n  AVG(cmcd_key_mtp),\n  COUNTIF( (cmcd_key_bs IS TRUE OR cmcd_key_sta = \"r\") AND cmcd_key_su IS NOT TRUE AND cmcd_key_ot = \"v\"),\n  COUNT(DISTINCT cmcd_key_sid)\nFROM\n  ${table_name}\nWHERE\n  $__timeFilter(request_datetime)\n  AND cmcd_key_url_domain IS NOT NULL\n  AND cmcd_key_ltc > 0 \n  AND cmcd_key_ltc < 15000  \n  AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n  AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n  AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n  AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')  \nGROUP BY\n  cmcd_key_url_domain"
    }
   ]
  },
  {
   "title": "CDN HTTP Response Codes (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "project": "ibc-2025-low-latency",
     "rawSql": "SELECT\n  $__timeGroup(request_datetime, '$time_aggregate') AS time,\n  SAFE_DIVIDE(COUNTIF(cmcd_key_rc >= 200 AND cmcd_key_rc < 300) * 100.0, COUNT(*)) AS HTTP_Success,\n  SAFE_DIVIDE(COUNTIF(cmcd_key_rc >= 400 AND cmcd_key_rc < 500) * 100.0, COUNT(*)) AS HTTP_Client_Error,\n  SAFE_DIVIDE(COUNTIF(cmcd_key_rc >= 500 AND cmcd_key_rc < 600) * 100.0, COUNT(*)) AS HTTP_Server_Error\nFROM\n  ${table_name}\nWHERE\n  $__timeFilter(request_datetime)\n  AND cmcd_key_rc IS NOT NULL\n  AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n  AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n  AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n  AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')  \nGROUP BY\n  time\nORDER BY\n  time"
    }
   ]
  },
  {
   "title": "CDN Time to First Byte",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "project": "ibc-2025-low-latency",
     "rawSql": "SELECT\n  $__timeGroup(request_datetime, '$time_aggregate') AS time,\n  AVG(cmcd_key_ttfb) AS avg_ttfb,\n  MIN(cmcd_key_ttfb) AS min_ttfb,\n  MAX(cmcd_key_ttfb) AS max_ttfb\nFROM\n  ${table_name}\nWHERE\n  $__timeFilter(request_datetime)\n  AND cmcd_key_ttfb IS NOT NULL\n  AND cmcd_key_ltc > 0\n  AND cmcd_key_ltc < 15000  \n  AND ('${cmcd_key_cid:raw}' = '__all__' OR cmcd_key_cid = '${cmcd_key_cid:raw}')\n  AND ('${cmcd_key_sid:raw}' = '__all__' OR cmcd_key_sid = '${cmcd_key_sid:raw}')\n  AND ('${request_country_code:raw}' = '__all__' OR request_country_code = '${request_country_code:raw}')\n  AND ('${request_browser_name:raw}' = '__all__' OR request_browser_name = '${request_browser_name:raw}')  \nGROUP BY\n  time\nORDER BY\n  time"
    }
   ]
  }
 ]
}