version: "3.8"

services:
  collector:
    command: npm run dev
    volumes:
      - ./collector:/app # Collector code is in a 'collector' directory

  gcloud-collector-function:
    volumes:
      - ./gcloud-collector-function:/app # Collector code is in a 'collector' directory

  player:
    volumes:
      - ./player:/app # Static files are in 'player'