version: "3.8"

services:
  collector:
    build: ./collector
    ports:
      - "3000:3000" # Expose the collector service on port 3000
    environment:
      - BIGQUERY_ENABLED=true
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/bigquery_secret_json
      - BIGQUERY_DATASET=cmcd
      - BIGQUERY_TABLE=cmcd_v2_data      
    secrets:
      - bigquery_secret_json
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224" 
        tag: "docker.collector.{{.Name}}" 
    depends_on:
      - fluentd
  influxdb:
    image: influxdb:2.7 
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-admin-token
    restart: unless-stopped
  fluentd:
    build: ./fluentd # Changed from image to build
    ports:
      - "24224:24224" 
      - "24224:24224/udp"
    volumes:
      - ./fluentd:/fluentd/etc 
      # - ./logs:/fluentd/log 
    depends_on:
      - influxdb
    environment: # Add these environment variables
      - FLUENT_INFLUXDB_TOKEN=my-super-secret-admin-token
      - FLUENT_INFLUXDB_ORG=my-org
      - FLUENT_INFLUXDB_BUCKET=my-bucket
    restart: unless-stopped
  grafana:
    image: grafana/grafana
    ports:
      - 8081:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_INSTALL_PLUGINS=grafana-bigquery-datasource
    secrets:
      - bigquery_secret_pem
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    depends_on:
      - influxdb

volumes:
  influxdb_data: {}

secrets:
  bigquery_secret_json:
    file: ./secrets/bigquery_secret.json
  bigquery_secret_pem:
    file: ./secrets/bigquery_secret.pem