version: "3.8"

services:
  collector:
    build: ./collector
    ports:
      - "3000:3000"
    environment:
      - LOCAL_ENABLED=true
      - LOCAL_FLUENTD_HOST=fluentd
      - LOCAL_FLUENTD_PORT=24224
      - LOCAL_FLUENTD_TAG=node.collector
    depends_on:
      - fluentd

  player:
    build: ./player
    ports:
      - "8080:3000"

  influxdb:
    image: influxdb:1.8
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=analytics
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin_password
    volumes:
      - influxdb_data:/var/lib/influxdb

  fluentd:
    platform: linux/arm64
    build: ./fluentd
    restart: unless-stopped
    volumes:
      - ./fluentd:/fluentd/etc
      - fluentd_buffer:/fluentd/log/buffer
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    environment:
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_DB=analytics
      - INFLUXDB_USER=admin
      - INFLUXDB_PASSWORD=admin_password
      - INFLUXDB_MEASUREMENT=cmcd_metrics
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana
    ports:
      - 8081:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana/local-stack:/etc/grafana/provisioning/datasources
      - ./grafana/local-stack/dashboards:/etc/grafana/provisioning/dashboards

volumes:
  influxdb_data:
  fluentd_buffer:
