apiVersion: 1

datasources:
- name: BigQuery DS
  type: grafana-bigquery-datasource
  editable: true
  enabled: true
  jsonData:
    authenticationType: jwt
    clientEmail: bigquery-data-editor@cmcdv2-bigquery.iam.gserviceaccount.com # Use the correct client email
    defaultProject: cmcdv2-bigquery # Use your project ID
    tokenUri: https://oauth2.googleapis.com/token
    privateKeyPath: '/run/secrets/bigquery_secret_pem'
- name: InfluxDB
  type: influxdb
  access: proxy
  url: http://influxdb:8086
  database: analytics
  isDefault: true