apiVersion: 1

datasources:
- name: InfluxDB
  type: influxdb
  url: http://influxdb:8086
  access: proxy 
  isDefault: true
  editable: true
  jsonData:
    version: Flux 
    organization: 'my-org' 
    defaultBucket: 'my-bucket' 
  secureJsonData:
    # This should be the token Grafana uses to connect to InfluxDB.
    # This is the DOCKER_INFLUXDB_INIT_ADMIN_TOKEN specified in the docker-compose.yml for InfluxDB.
    token: 'my-super-secret-admin-token'
- name: BigQuery DS
  type: grafana-bigquery-datasource
  editable: true
  enabled: true # Assuming BigQuery is still desired
  jsonData:
    authenticationType: jwt
    clientEmail: bigquery-data-editor@cmcdv2-bigquery.iam.gserviceaccount.com
    defaultProject: cmcdv2-bigquery
    tokenUri: https://oauth2.googleapis.com/token
    # The path for privateKeyPath should be accessible within the Grafana container.
    # The docker-compose mounts secrets to /run/secrets/bigquery_secret_pem
    privateKeyPath: '/run/secrets/bigquery_secret_pem'